const everything = [
    {
        name: "shao wee wee", 
        breed: "loser",
        price: "worthless", 
        personality: "slow",
        petimage: "https://media.discordapp.net/attachments/1167647678356799520/1180909309148811304/IMG_4359.jpg?ex=657f227f&is=656cad7f&hm=f4e7cedbe60d920a44982657ca6bd344a48fe3972db8a47faf7dee50d392c5ab&=&format=webp&width=463&height=617",
        type: ['special'],
    },
    {
        name: "LAALAA",
        breed: "afghan hound",
        price: "$2000", 
        personality: "Aloof",
        petimage: "https://www.petmiconnect.com/wp-content/uploads/2018/08/ah.jpg",
        type: ['dawg'],
    },
    {
        name: "DIPSY",
        breed: "alaskan klee kai",
        price: "$1800", 
        personality: "Playful",
        petimage: "https://wagsandwiggles.com/wp-content/uploads/2023/03/Sandy-1-scaled.jpg",
        type: ['dawg'],
    },
    {
        name: "PO",
        breed: "akita",
        price: "$2300", 
        personality: "Docile",
        petimage: "https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2023-05/image-text-component-akita-2.jpg?h=2d6b2090&itok=24Vze-U4",
        type: ['dawg'],
    },
    {
        name: "TINKYWINKY",
        breed:  "tosa",
        price: "$1950", 
        personality: "Tranquil",
        petimage: "https://images.saymedia-content.com/.image/t_share/MTc0OTY5MDgwMjAwMTc3NjMy/japanese-tosa-dog-breed.jpg",
        type: ['dawg'],
    },
    {
        name: "Arby's",
        breed: "persian",
        price: "$1300", 
        personality: "Calm",
        petimage: "https://www.thesprucepets.com/thmb/5OSN_p9hUfPssKsJORQDGnAz_tQ=/1963x0/filters:no_upscale():strip_icc()/GettyImages-181861505-4e63227ed0a14dc9bfe86848ef54caf3.jpg",
        type: ['meow'],
    }, 
    {
        name: "Burger King",
        breed: "ragdoll",
        price: "$650", 
        personality: "Friendly",
        petimage: "https://cdn.shopify.com/s/files/1/0435/0466/4732/files/pros_and_cons_of_ragdoll_cats_1_600x600.jpg?v=1651120241",
        type: ['meow'],
    },
    {
        name: "Chipotle Mexican Grill",
        breed: "maine coon",
        price: "$1700", 
        personality: "Goofy",
        petimage: "https://www.thesprucepets.com/thmb/MzKr6fC-v8W4D4oz2p9wWCwAFms=/2119x0/filters:no_upscale():strip_icc()/GettyImages-1189893683-e0ff70596b3b4f0687ba573e5a671f74.jpg",
        type: ['meow'],
    },
    {
        name: "Domino's Pizza",
        breed:"birman",
        price: "$2400", 
        personality: "Affectionate",
        petimage: "https://geniusvets.s3.amazonaws.com/gv-cat-breeds/Birman-1.jpg",
        type: ['meow'],
    }, 
    {
        name: "Five Guys",
        breed: "siamese",
        price: "$675", 
        personality: "Extroverted",
        petimage: "https://icatcare.org/app/uploads/2018/10/Siamese.png",
        type: ['meow'],
    },
    {
        name: "PlayStation 2",
        breed: "parrot",
        price: "$1200", 
        personality: "Cuddly",
        petimage: "https://parrotjunkie.com/cdn/shop/articles/2.png?v=1686711674&width=1100",
        type: ['chirp'],
    },
    {
        name: "Gamecube",
        breed: "cockatiel",
        price: "$275", 
        personality: "Gentle",
        petimage: "https://animal-world.com/wp-content/uploads/2023/08/grey-cockatiel-opening-its-wings_Jolanta-Beinarovica_Shutterstock.jpg",
        type: ['chirp'],
    },
    {
        name: "Xbox 360",
        breed: "finch",
        price: "$95", 
        personality: "Energetic",
        petimage: "https://upload.wikimedia.org/wikipedia/commons/d/de/Bullfinch_male.jpg",
        type: ['chirp'],
    }, 
    {
        name: "Wii",
        breed: "canary",
        price: "$365", 
        personality: "Quiet",
        petimage: "https://www.singing-wings-aviary.com/wp-content/uploads/2016/09/Gloster-Canary.jpg",
        type: ['chirp'],
    },
    {
        name: "Nintendo DS and Nintendo Switch",
        breed: "pair of barbary doves",
        price: "$145", 
        personality: "Tame",
        petimage: "https://blog.nature.org/wp-content/uploads/2014/02/eurasian-collared-dove.jpg",
        type: ['chirp'],
    }, 
];

export {everything};